/**
 * Generates supabase/migrations/012_packages_table.sql — the packages table
 * schema PLUS a full seed of all 23 current packages (100% of their data:
 * text, tags, hero images, per-day photos, maps).
 *
 *   npx tsx scripts/generate-package-seed.ts            # (re)write the migration file
 *   npx tsx scripts/generate-package-seed.ts --verify   # after applying it in Supabase,
 *                                                        # deep-compare DB rows vs source
 *
 * Design: we IMPORT the real TS data modules so V8 decodes the •/–/...
 * escapes and trailing commas for us — we never hand-escape unicode. SQL is made
 * safe with Postgres dollar-quoting (nonce tags), so apostrophes / & / slashes in
 * the travel copy need no escaping.
 */
import fs from 'node:fs';
import path from 'node:path';
import { tourDetails, type TourDetail } from '../app/tours/tour-data';
import { cityHighlights } from '../app/tours/city-highlights';

type Highlight = { label: string; image: string };
type SeedDay = { title: string; description: string; highlights: Highlight[] };

const OUT_FILE = path.join(__dirname, '..', 'supabase', 'migrations', '012_packages_table.sql');

// --- City matching: replicate the tour detail page exactly (longest key first,
//     lowercase substring of the day title, first day per city wins). ---
const CITY_NAMES = Object.keys(cityHighlights);
function matchCity(title: string): string | null {
  const sorted = [...CITY_NAMES].sort((a, b) => b.length - a.length);
  for (const c of sorted) {
    if (title.toLowerCase().includes(c.toLowerCase())) return c;
  }
  return null;
}

// --- Rich-text conversion: plain/bulleted source text -> HTML that TipTap edits
//     and the site renders inside a `prose` container. `•`-prefixed lines
//     become <li> inside a <ul>; other non-empty lines become <p>. ---
function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
function textToHtml(text: string): string {
  const lines = text.split('\n');
  const out: string[] = [];
  let bullets: string[] = [];
  const flush = () => {
    if (bullets.length) {
      out.push('<ul>' + bullets.map((b) => `<li>${escapeHtml(b)}</li>`).join('') + '</ul>');
      bullets = [];
    }
  };
  for (const raw of lines) {
    const line = raw.trim();
    if (!line) {
      flush();
      continue;
    }
    if (line.startsWith('•')) {
      bullets.push(line.replace(/^•\s*/, ''));
    } else {
      flush();
      out.push(`<p>${escapeHtml(line)}</p>`);
    }
  }
  flush();
  return out.join('');
}

// --- Build the per-package seed shape (days now carry their own photos). ---
function buildDays(pkg: TourDetail): SeedDay[] {
  const shown = new Set<string>();
  return pkg.days.map((d) => {
    let highlights: Highlight[] = [];
    const city = matchCity(d.title);
    if (city && !shown.has(city)) {
      const hl = cityHighlights[city] ?? [];
      if (hl.length > 0) {
        shown.add(city);
        highlights = hl.map((h) => ({ label: h.label, image: h.image }));
      }
    }
    return { title: d.title, description: textToHtml(d.description), highlights };
  });
}

// --- SQL literal helpers ---
function dq(s: string): string {
  let tag = 'x';
  while (s.includes(`$${tag}$`)) tag += 'x';
  return `$${tag}$${s}$${tag}$`;
}
function textOrNull(s: string | undefined | null): string {
  if (s === undefined || s === null || s === '') return 'NULL';
  return dq(s);
}
function textArray(arr: string[] | undefined): string {
  if (!arr || arr.length === 0) return 'ARRAY[]::text[]';
  return `ARRAY[${arr.map(dq).join(', ')}]::text[]`;
}
function jsonbLit(value: unknown): string {
  const json = JSON.stringify(value);
  let tag = 'j';
  while (json.includes(`$${tag}$`)) tag += 'j';
  return `$${tag}$${json}$${tag}$::jsonb`;
}

const SCHEMA = `-- Migration: Packages table (tour packages, formerly hard-coded in
-- app/tours/tour-data.ts + per-day photos from app/tours/city-highlights.ts).
-- Run this in the Supabase SQL Editor.
--
-- The seed at the bottom carries all 23 original packages over verbatim,
-- including hero images, per-day itinerary photos, journey maps and all tags.
-- It is generated by scripts/generate-package-seed.ts — do not hand-edit the
-- INSERTs; re-run that script instead.

-- 1. Create packages table
CREATE TABLE IF NOT EXISTS packages (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug           TEXT NOT NULL UNIQUE,          -- URL code, e.g. /tours/<slug>
  title          TEXT NOT NULL,
  starting_price TEXT,                          -- display string like "$290"; NULL if unpriced
  description    TEXT NOT NULL,                 -- HTML (rendered in a prose container)
  days           JSONB NOT NULL DEFAULT '[]'::jsonb,  -- [{title, description(html), highlights:[{label,image}]}]
  inclusions     TEXT[] NOT NULL DEFAULT '{}',
  images         TEXT[] NOT NULL DEFAULT '{}',  -- ordered; images[0] = card / carousel-first
  map_image      TEXT,                          -- filename (legacy /public) OR full bucket URL
  countries      TEXT[] NOT NULL DEFAULT '{}',
  destinations   TEXT[] NOT NULL DEFAULT '{}',
  themes         TEXT[] NOT NULL DEFAULT '{}',
  religions      TEXT[] NOT NULL DEFAULT '{}',
  activities     TEXT[] NOT NULL DEFAULT '{}',
  sort_order     INTEGER NOT NULL DEFAULT 0,    -- stable list order (seeded to source order)
  is_published   BOOLEAN NOT NULL DEFAULT true,
  created_at     TIMESTAMPTZ DEFAULT now(),
  updated_at     TIMESTAMPTZ DEFAULT now()
);

-- 2. Indexes
CREATE INDEX IF NOT EXISTS idx_packages_published  ON packages(is_published);
CREATE INDEX IF NOT EXISTS idx_packages_sort_order ON packages(sort_order);
CREATE INDEX IF NOT EXISTS idx_packages_slug       ON packages(slug);

-- 3. Enable RLS
ALTER TABLE packages ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies (matches the Articles model: public sees published rows,
--    any authenticated admin can manage — no allowlist).
DROP POLICY IF EXISTS "Public can view published packages" ON packages;
CREATE POLICY "Public can view published packages"
  ON packages FOR SELECT
  USING (is_published = true);

DROP POLICY IF EXISTS "Authenticated users can manage packages" ON packages;
CREATE POLICY "Authenticated users can manage packages"
  ON packages FOR ALL
  USING (auth.role() = 'authenticated');

-- 5. Seed all 23 packages.
--    ON CONFLICT (slug) DO NOTHING keeps this safely re-runnable: once an admin
--    edits a package in the dashboard, re-running this file will NOT clobber it.
`;

function insertFor(pkg: TourDetail, index: number): string {
  const days = buildDays(pkg);
  return `-- ${index + 1}. ${pkg.id} — ${pkg.title}
INSERT INTO packages (slug, title, starting_price, description, days, inclusions, images, map_image, countries, destinations, themes, religions, activities, sort_order, is_published)
VALUES (
  ${dq(pkg.id)},
  ${dq(pkg.title)},
  ${textOrNull(pkg.startingPrice)},
  ${dq(textToHtml(pkg.description))},
  ${jsonbLit(days)},
  ${textArray(pkg.inclusions)},
  ${textArray(pkg.images)},
  ${textOrNull(pkg.mapImage)},
  ${textArray(pkg.countries)},
  ${textArray(pkg.destinations)},
  ${textArray(pkg.themes)},
  ${textArray(pkg.religions)},
  ${textArray(pkg.activities)},
  ${index},
  true
)
ON CONFLICT (slug) DO NOTHING;`;
}

function generate() {
  const inserts = tourDetails.map((p, i) => insertFor(p, i)).join('\n\n');
  const sql = `${SCHEMA}\n${inserts}\n`;
  fs.writeFileSync(OUT_FILE, sql, 'utf8');

  // Inventory so completeness is visible, not assumed.
  let heroImgs = 0;
  let dayPhotos = 0;
  let maps = 0;
  const noPrice: string[] = [];
  tourDetails.forEach((p) => {
    heroImgs += (p.images ?? []).length;
    buildDays(p).forEach((d) => (dayPhotos += d.highlights.length));
    if (p.mapImage) maps += 1;
    if (!p.startingPrice) noPrice.push(p.id);
  });

  console.log(`✔ Wrote ${path.relative(process.cwd(), OUT_FILE)}`);
  console.log(`  packages:          ${tourDetails.length}`);
  console.log(`  hero images:       ${heroImgs}`);
  console.log(`  per-day photos:    ${dayPhotos}`);
  console.log(`  packages w/ map:   ${maps}`);
  console.log(`  no startingPrice:  ${noPrice.length ? noPrice.join(', ') : 'none'}`);
  console.log('\nNext: run 012 + 013 in the Supabase SQL Editor, then `--verify`.');
}

// --- Verify: after the migration is applied, re-fetch and deep-compare. ---
function eqArr(a: unknown[] = [], b: unknown[] = []): boolean {
  return JSON.stringify(a) === JSON.stringify(b);
}

async function verify() {
  const dotenv = await import('dotenv');
  dotenv.config({ path: '.env.local' });
  const { createClient } = await import('@supabase/supabase-js');
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !key) {
    console.error('Missing NEXT_PUBLIC_SUPABASE_URL / NEXT_PUBLIC_SUPABASE_ANON_KEY in .env.local');
    process.exit(1);
  }
  const supabase = createClient(url, key, { auth: { persistSession: false } });
  const { data, error } = await supabase.from('packages').select('*').order('sort_order', { ascending: true });
  if (error) {
    console.error('Query failed (did you run migration 012 in Supabase?):', error.message);
    process.exit(1);
  }
  const rows = data ?? [];
  const bySlug = new Map(rows.map((r: any) => [r.slug, r]));

  const problems: string[] = [];
  if (rows.length !== tourDetails.length) {
    problems.push(`row count ${rows.length} != source ${tourDetails.length}`);
  }
  for (const pkg of tourDetails) {
    const r = bySlug.get(pkg.id);
    if (!r) {
      problems.push(`MISSING: ${pkg.id}`);
      continue;
    }
    const expectDays = buildDays(pkg);
    const checks: [string, boolean][] = [
      ['title', r.title === pkg.title],
      ['starting_price', (r.starting_price ?? null) === (pkg.startingPrice ?? null)],
      ['description', r.description === textToHtml(pkg.description)],
      ['map_image', (r.map_image ?? null) === (pkg.mapImage ?? null)],
      ['inclusions', eqArr(r.inclusions, pkg.inclusions)],
      ['images', eqArr(r.images, pkg.images)],
      ['countries', eqArr(r.countries, pkg.countries ?? [])],
      ['destinations', eqArr(r.destinations, pkg.destinations ?? [])],
      ['themes', eqArr(r.themes, pkg.themes ?? [])],
      ['religions', eqArr(r.religions, pkg.religions ?? [])],
      ['activities', eqArr(r.activities, pkg.activities ?? [])],
      ['days', JSON.stringify(r.days) === JSON.stringify(expectDays)],
    ];
    for (const [field, ok] of checks) {
      if (!ok) problems.push(`${pkg.id}: ${field} mismatch`);
    }
  }

  if (problems.length) {
    console.error(`x VERIFY FAILED (${problems.length} issue(s)):`);
    problems.slice(0, 40).forEach((p) => console.error('  - ' + p));
    process.exit(1);
  }
  console.log(`✔ VERIFY PASSED — ${rows.length} packages match source 100% (text, tags, images, per-day photos).`);
}

if (process.argv.includes('--verify')) {
  verify();
} else {
  generate();
}
