-- Create the inquiries table
create table public.inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text,
  message text not null,
  status text default 'pending' check (status in ('pending', 'contacted', 'resolved', 'spam'))
);

-- Enable Row Level Security
alter table public.inquiries enable row level security;

-- Create policy to allow anyone (anon) to insert inquiries
create policy "Enable insert for everyone" on public.inquiries
  for insert
  with check (true);

-- Create policy to allow only authenticated users to view inquiries
-- This assumes you will use Supabase Auth for your admin panel
create policy "Enable read access for authenticated users" on public.inquiries
  for select
  using (auth.role() = 'authenticated');

-- Create policy to allow authenticated users to update (e.g. change status)
create policy "Enable update for authenticated users" on public.inquiries
  for update
  using (auth.role() = 'authenticated');
